<?php
session_start();
require "connection.php";
if (isset($_SESSION["jd_admin"])) {

	$admin = $_SESSION["jd_admin"];
	$autoGeneratedPassword = uniqid() . $admin["id"];

	$d = new DateTime();
	$tz = new DateTimeZone("Asia/Colombo");
	$d->setTimezone($tz);
	$today = $d->format("Y-m-d");

?>

	<!DOCTYPE html>
	<html lang="en">

	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<title>Jade Times - Manage Certificates / Documents Section</title>

		<!-- Meta -->
		<meta name="description" content="Marketplace for Bootstrap Admin Dashboards" />
		<meta name="author" content="Bootstrap Gallery" />
		<link rel="canonical" href="https://www.bootstrap.gallery/">
		<meta property="og:url" content="https://www.bootstrap.gallery">
		<meta property="og:title" content="Admin Templates - Dashboard Templates | Bootstrap Gallery">
		<meta property="og:description" content="Marketplace for Bootstrap Admin Dashboards">
		<meta property="og:type" content="Website">
		<meta property="og:site_name" content="Bootstrap Gallery">
		<link rel="icon" href="assets/img/iconImg.jpg" />

		<!-- *************
			************ CSS Files *************
		************* -->
		<link rel="stylesheet" href="assets/fonts/bootstrap/bootstrap-icons.css" />
		<link rel="stylesheet" href="assets/css/main.css" />

		<!-- *************
			************ Vendor Css Files *************
		************ -->

		<!-- Scrollbar CSS -->
		<link rel="stylesheet" href="assets/vendor/overlay-scroll/OverlayScrollbars.min.css" />
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/css/selectize.bootstrap3.min.css" integrity="sha256-ze/OEYGcFbPRmvCnrSeKbRTtjG4vGLHXgOqsyLFTRjg=" crossorigin="anonymous" />
		<link rel="stylesheet" href="assets/css/admin.css" />
	</head>

	<body class="backgroundColorChange" onload="loadUserFeedbacksAndAttachements(0)">

		<!-- Page wrapper start -->
		<div class="page-wrapper">

			<!-- Main container start -->
			<div class="main-container">
				<?php require "adminSideBar.php" ?>


				<!-- App container starts -->
				<div class="app-container">

					<!-- App header starts -->
					<?php require "adminAppHeader.php" ?>
					<!-- App header ends -->

					<!-- App hero header starts -->
					<div class="app-hero-header d-flex align-items-start">

						<!-- Breadcrumb start -->
						<ol class="breadcrumb d-none d-lg-flex align-items-center">
							<li class="breadcrumb-item">
								<i class="bi bi-house text-dark"></i>
								<a href="adminPanel.php">Home</a>
							</li>
							<li class="breadcrumb-item">
								<i class="bi bi-building text-dark"></i>
								<a href="manageDocsAndFeedbacks.php">Documents & Feedbacks</a>
							</li>
							<li class="breadcrumb-item" aria-current="page">Manage Cetificates Feedbacks</li>
						</ol>
						<!-- Breadcrumb end -->

					</div>
					<!-- App Hero header ends -->

					<!-- App body starts -->
					<div class="app-body" id="cbody">
						<?php

						$userResultAttendance = Database::operation("SELECT * FROM `user`", "s");
						$addNewList = $userResultAttendance;
						?>


						<div class="row">
							<div class="col-12">
								<p class="d-inline-flex gap-1">

									<button type="button" class="btn btn-dark backgroundColorChange removeCorner" data-bs-toggle="modal" data-bs-target="#staticBackdrop2">
										<i class="bi bi-filetype-doc"></i> Upload Service Letter And Cetificate
									</button>

								</p>
							</div>
							<!-- Button trigger modal -->

							<!-- Add Docs -->
							<div class="modal fade" id="staticBackdrop2" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
								<div class="modal-dialog">
									<div class="modal-content">
										<div class="modal-header">
											<h5 class="modal-title" id="staticBackdropLabel">Upload Service Letter And Cetificate</h5>
											<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
										</div>
										<div class="modal-body">
											<div class="row">
												<div class="col-12">
													<div class="alert alert-danger d-none" id="infoMessage" role="alert">
													</div>
												</div>
												<div class="col-12">
													<div class="mb-3">
														<label class="form-label">Name</label>
														<select class="form-select removeCorner" id="requestUser">
															<option value="0">Select user</option>
															<?php
															if ($addNewList->num_rows != 0) {
																for ($adi = 0; $adi < $addNewList->num_rows; $adi++) {
																	$userselect = $addNewList->fetch_assoc();

															?>
																	<option value="<?php echo $userselect["id"] ?>"><?php echo $userselect["fname"] . " " . $userselect["lname"] . " " . $userselect["jid"] ?></option>
															<?php
																}
															}

															?>
														</select>
													</div>
												</div>


												<div class="col-12">
													<div class="mb-3">
														<label class="form-label">Cetificate</label>
														<input type="file" id="catificateField" class="form-control removeCorner" value="" />
													</div>
												</div>

												<div class="col-12">
													<div class="mb-3">
														<label class="form-label">Service Letter</label>
														<input type="file" id="serviceLetterField" class="form-control removeCorner" value="" />
													</div>
												</div>

												<div class="col-12">
													<div class="mb-3">
														<button type="button" class="w-100 btn btn-dark backgroundColorChange" onclick="adminAddFeedbackRequest()">Upload</button>
													</div>
												</div>
											</div>
										</div>
										<div class="modal-footer">
											<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>

										</div>
									</div>
								</div>
							</div>


							<!-- Modal -->

						</div>

						<div class="row">
							<div class="col-lg-3 col-sm-4 col-12">
								<div class="mb-3">
									<div class="row">
										<div class="col-12"><label class="form-label fs-6">Search By :</label></div>

									</div>


								</div>
							</div>
						</div>



						<!-- Row start -->
						<div class="row ">

							<div class="col-lg-3 col-sm-4 col-12 text-center">
								<div class="mb-3">
									<div class="row">
										<div class="col-3 text-end"><label class="form-label smallText">Name -</label></div>


										<div class="col-9">
											<select id="select-state" class="form-select removeCorner smallText" onchange="loadUserFeedbacksAndAttachements(1)">
												<option value="0">All users</option>
												<?php



												$userResultAttendance = Database::operation("SELECT * FROM `user`", "s");
												$userResultAttendanceNumbers = $userResultAttendance->num_rows;
												if ($userResultAttendanceNumbers != 0) {
													for ($typ = 0; $typ < $userResultAttendanceNumbers; $typ++) {
														$userselect = $userResultAttendance->fetch_assoc();

												?>
														<option value="<?php echo $userselect["id"] ?>"><?php echo $userselect["fname"] . " " . $userselect["lname"] . " " . $userselect["jid"] ?></option>
												<?php
													}
												}
												?>
											</select>
										</div>


									</div>




								</div>
							</div>



							
							<div class="col-lg-6 col-12 text-center mt-lg-0 mt-3">
								<div class="mb-3">
									<div class="row">
										<div class="col-3 text-end"><label class="form-label smallText">Feedback Status -</label></div>


										<div class="col-9">
											<select id="status" class="form-select removeCorner smallText" onchange="loadUserFeedbacksAndAttachements(1)">
												<option value="0">All</option>
												<option value="1">Complete</option>
												<option value="2">Pending</option>
												
											</select>
										</div>


									</div>




								</div>
							</div>

						</div>

						<div class="col-xxl-12">
							<div class="card mb-4">
								<div class="card-body">
									<div class="row">

										<div class="table-responsive">
											<table class="table align-middle table-hover m-0">
												<thead>
													<tr>
														<th scope="col">No</th>

														<th scope="col">Name</th>
														<th scope="col">Email</th>
														<th scope="col">Feedback</th>
														<th scope="col">Ratings</th>
														

													</tr>
												</thead>
												<tbody id="tableBodyUser">

												</tbody>
											</table>
										</div>
									</div>
									<div class="row mt-3">
										<div class="col-12 text-center">
											<!-- Card start -->
											<div class="card mb-4">
												<div class="card-body">
													<div class="btn-group" role="group" aria-label="Basic checkbox toggle button group" id="pagicontainer">

													</div>
												</div>
											</div>
											<!-- Card end -->
										</div>
									</div>
								</div>
							</div>

						</div>
						<!-- Row end -->

					</div>
					<!-- App body ends -->

					<!-- App footer start -->
					<div class="app-footer">
						<span>© 2024 Jadetimes Media LLC. All rights reserved.</span>
					</div>
					<!-- App footer end -->

				</div>
				<!-- App container ends -->

			</div>
			<!-- Main container end -->

		</div>
		<!-- Page wrapper end -->

		<!-- *************
			************ JavaScript Files *************
		************* -->
		<!-- Required jQuery first, then Bootstrap Bundle JS -->
		<script src="assets/js/jquery.min.js"></script>
		<script src="assets/js/bootstrap.bundle.min.js"></script>

		<!-- *************
			************ Vendor Js Files *************
		************* -->

		<!-- Overlay Scroll JS -->
		<script src="assets/vendor/overlay-scroll/jquery.overlayScrollbars.min.js"></script>
		<script src="assets/vendor/overlay-scroll/custom-scrollbar.js"></script>

		<!-- Custom JS files -->
		<script src="assets/js/custom.js"></script>

		<script src="assets/js/admin.js"></script>
		<!-- Bootstrap JS and dependencies -->
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


		<!-- Custom JS -->
		<script>
		


			function loadDocumentTypes() {


				var tablebody = document.getElementById("tableBodyUser");
				tablebody.innerHTML = "";
				fetch(baseUrl + "documentLoadProcess.php", {
						method: "GET",

					}).then(function(resp) {
						return resp.json();

					})
					.then(function(value) {

						var table = document.getElementById('docTypeDiv');
						table.innerHTML = "";
						var docSelect = document.getElementById("docTypeSelect");
						docSelect.innerHTML = '<option value="0">Select Type</option>';

						if (value.type == "success") {



							for (var tl = 0; tl < value.message.length; tl++) {
								table.innerHTML = table.innerHTML + `
	<tr>
																		<td>${value.message[tl][0]}</td>
																		<td>${value.message[tl][1]}</td>
																	</tr>
`;



								docSelect.innerHTML = docSelect.innerHTML + `
								<option value="${value.message[tl][0]}">${value.message[tl][1]}</option>`;
							}



						} else if (value.type = "error") {

							table.innerHTML = value.message;

						}
					})
					.catch(function(error) {
						console.log(error);
					});



			}

			loadDocumentTypes();



			function adminAddFeedbackRequest() {
				let requestUser = document.getElementById("requestUser");
				let catificateField = document.getElementById("catificateField");
				let serviceLetterField = document.getElementById("serviceLetterField");
				let cbody = document.getElementById("cbody");


				let message = document.getElementById("infoMessage");





				if (requestUser.value == 0) {

					message.innerHTML = "Select A User";
					message.classList = "alert alert-danger";
					backToTop(cbody);

				} else if (!catificateField.files[0]) {
					message.innerHTML = "Add the Cetificate";
					message.classList = "alert alert-danger";
					backToTop(cbody);

				} else if (!serviceLetterField.files[0]) {
					message.innerHTML = "Add the Service Letter";
					message.classList = "alert alert-danger";
					backToTop(cbody);

				} else {

					message.innerHTML = "";
					message.classList = "";


					var formData = new FormData();

					formData.append("user", requestUser.value);

					formData.append("cetificate", catificateField.files[0]);
					formData.append("serviceLetter", serviceLetterField.files[0]);




					fetch(baseUrl + "adminServiceCetificatesAddProcess.php", {
							method: "POST",
							body: formData,

						}).then(function(resp) {
							return resp.json();

						})
						.then(function(value) {

							if (value.type == "success") {
								message.innerHTML = value.message;
								message.classList = "alert alert-success";
								backToTop(cbody);
								setTimeout(() => {
									requestUser.value = 0;
									catificateField.value = null;
									serviceLetterField.value = null;

									loadUserFeedbacksAndAttachements(2);
								}, 2000)

							} else if (value.type == "error") {
								message.innerHTML = value.message;
								message.classList = "alert alert-danger";
								backToTop(cbody);
							}

						})
						.catch(function(error) {
							console.log(error);
						});

				}



			}


			function loadUserFeedbacksAndAttachements(stat) {


				var selectUser = document.getElementById("select-state");

				
				var status = document.getElementById("status");




				var ele = document.getElementsByName('btnradio');
				var dip = ""
				for (i = 0; i < ele.length; i++) {
					if (ele[i].checked) {
						dip = ele[i].value;
					}

				}
				var page = 1;

				if (stat == 2) {
					var pagi = document.getElementsByName('pagi');

					for (j = 0; j < pagi.length; j++) {
						if (pagi[j].checked) {
							page = Number(pagi[j].value);
						}

					}
				}


				var formData = new FormData();
				formData.append("selectUser", selectUser.value);
	
				formData.append("status", status.value);
				formData.append("page", page);






				var tablebody = document.getElementById("tableBodyUser");
				tablebody.innerHTML = "";
				fetch(baseUrl + "usefeedbackAndAttachementLoadProcess.php", {
						method: "POST",
						body: formData,


					}).then(function(resp) {
						return resp.json();

					})
					.then(function(value) {

						var pagicontainer = document.getElementById('pagicontainer');
						pagicontainer.innerHTML = "";

						if (value.type == "success") {
							var userSearchData = value.message;

							for (let index = 0; index < userSearchData.length; index++) {
								const user = userSearchData[index];

								const newRow = document.createElement('tr');
						
								const nocell = document.createElement('td');
								nocell.textContent = index + 1;
								const idCell = document.createElement('td');
								idCell.textContent = user.fname + " " + user.lname;

								const roleCell = document.createElement('td');
								roleCell.textContent = user.email;

								const addressCell = document.createElement('td');
								const endDateCell = document.createElement('td');

								if (user.status == "0") {
									addressCell.textContent = "pending";
									addressCell.classList = "bg-danger";


									endDateCell.textContent = "pending";
									endDateCell.classList = "bg-danger";
								} else {
									addressCell.textContent = user.feedback;
									endDateCell.textContent = user.rating;
									
								}


								
								



								newRow.appendChild(nocell);
								newRow.appendChild(idCell);
								newRow.appendChild(roleCell);
								newRow.appendChild(addressCell);


								newRow.appendChild(endDateCell);
							

								tablebody.appendChild(newRow);
							}


							var btnCount = value.buttoncount;


							var firstpagi = document.createElement('input');
							firstpagi.type = 'radio';
							firstpagi.className = 'btn-check';
							firstpagi.name = 'pagi';
							firstpagi.id = 'firstpagi';

							firstpagi.value = 1;
							firstpagi.onchange = function() {
								loadUserFeedbacksAndAttachements(2);
							}



							var firstlabel = document.createElement('label');
							firstlabel.className = 'btn btn-outline-info removeCorner';
							firstlabel.htmlFor = 'firstpagi';
							firstlabel.innerText = "First";



							pagicontainer.appendChild(firstpagi);
							pagicontainer.appendChild(firstlabel);



							var startPage = 1;

							var endpage = 5;



							var val = page + 4;





							if ((page + 4) < btnCount) {
								endpage = page + 4;
								startPage = page;

							} else {

								if (btnCount >= 5) {
									startPage = btnCount - 4;

								} else {

									startPage = 1;

								}
								endpage = btnCount;
							}



							if (page != 1 && btnCount > 5) {
								var frontPagi = document.createElement('input');
								frontPagi.type = 'radio';
								frontPagi.className = 'btn-check';
								frontPagi.name = 'pagi';
								frontPagi.id = 'btnpagifront';

								frontPagi.value = Number(startPage) - 1;
								frontPagi.onchange = function() {
									loadUserFeedbacksAndAttachements(2);
								}

								var labelfrontpagi = document.createElement('label');
								labelfrontpagi.className = 'btn btn-outline-info removeCorner';
								labelfrontpagi.htmlFor = 'btnpagifront';
								labelfrontpagi.innerText = Number(startPage) - 1;



								pagicontainer.appendChild(frontPagi);
								pagicontainer.appendChild(labelfrontpagi);

							}

							for (let i = startPage - 1; i < endpage; i++) {



								var radioButton = document.createElement('input');
								radioButton.type = 'radio';
								radioButton.className = 'btn-check';
								radioButton.name = 'pagi';
								radioButton.id = 'btnpagi' + i;
								var pageVal = i + 1;
								radioButton.value = pageVal;
								radioButton.onchange = function() {
									loadUserFeedbacksAndAttachements(2);
								}
								if (page == pageVal) {
									radioButton.checked = true;
								}


								var label = document.createElement('label');
								label.className = 'btn btn-outline-info removeCorner';
								label.htmlFor = 'btnpagi' + i;
								label.innerText = pageVal;



								pagicontainer.appendChild(radioButton);
								pagicontainer.appendChild(label);

							}


							var lastpagi = document.createElement('input');
							lastpagi.type = 'radio';
							lastpagi.className = 'btn-check';
							lastpagi.name = 'pagi';
							lastpagi.id = 'lastpagi';

							lastpagi.value = btnCount;
							lastpagi.onchange = function() {
								loadUserFeedbacksAndAttachements(2);
							}



							var lastlabel = document.createElement('label');
							lastlabel.className = 'btn btn-outline-info removeCorner';
							lastlabel.htmlFor = 'lastpagi';
							lastlabel.innerText = "Last (" + btnCount + ")";



							pagicontainer.appendChild(lastpagi);
							pagicontainer.appendChild(lastlabel);




						} else if (value.type = "error") {

							tablebody.innerHTML = value.message;

						}
					})
					.catch(function(error) {
						console.log(error);
					});



			}
		</script>
	</body>

	</html>
<?php

} else {
?>
	<script>
		window.location = "adminLogin.php"
	</script>
<?php
}
?>