<?php
session_start();
require "connection.php";
if (isset($_SESSION["jd_user"])) {
	$admin = $_SESSION["jd_user"];
	if ($admin["user_type"] == "head") {



		$autoGeneratedPassword = uniqid() . $admin["id"];

		$d = new DateTime();
		$tz = new DateTimeZone("Asia/Colombo");
		$d->setTimezone($tz);
		$today = $d->format("Y-m-d");

?>

		<!DOCTYPE html>
		<html lang="en">

		<head>
			<meta charset="utf-8" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<title>Jade Times -Head Attendance view /add </title>

			<!-- Meta -->
			<meta name="description" content="Marketplace for Bootstrap Admin Dashboards" />
			<meta name="author" content="Bootstrap Gallery" />
			<link rel="canonical" href="https://www.bootstrap.gallery/">
			<meta property="og:url" content="https://www.bootstrap.gallery">
			<meta property="og:title" content="Admin Templates - Dashboard Templates | Bootstrap Gallery">
			<meta property="og:description" content="Marketplace for Bootstrap Admin Dashboards">
			<meta property="og:type" content="Website">
			<meta property="og:site_name" content="Bootstrap Gallery">
			<link rel="icon" href="assets/img/iconImg.jpg" />

			<!-- *************
			************ CSS Files *************
		************* -->
			<link rel="stylesheet" href="assets/fonts/bootstrap/bootstrap-icons.css" />
			<link rel="stylesheet" href="assets/css/main.css" />

			<!-- *************
			************ Vendor Css Files *************
		************ -->

			<!-- Scrollbar CSS -->
			<link rel="stylesheet" href="assets/vendor/overlay-scroll/OverlayScrollbars.min.css" />
			<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/css/selectize.bootstrap3.min.css" integrity="sha256-ze/OEYGcFbPRmvCnrSeKbRTtjG4vGLHXgOqsyLFTRjg=" crossorigin="anonymous" />
			<link rel="stylesheet" href="assets/css/user.css" />
		</head>

		<body class="backgroundColorChange" onload="loadUserAttendanceHead(0)">

			<!-- Page wrapper start -->
			<div class="page-wrapper">

				<!-- Main container start -->
				<div class="main-container">
					<?php require "userSideBar.php" ?>


					<!-- App container starts -->
					<div class="app-container">

						<!-- App header starts -->
						<?php require "userAppHeader.php" ?>
						<!-- App header ends -->

						<!-- App hero header starts -->
						<div class="app-hero-header d-flex align-items-start">

							<!-- Breadcrumb start -->
							<ol class="breadcrumb d-none d-lg-flex align-items-center">
								<li class="breadcrumb-item">
									<i class="bi bi-house text-dark"></i>
									<a href="userDashBoard.php">Home</a>
								</li>
								<li class="breadcrumb-item" aria-current="page">department Attendance</li>
							</ol>
							<!-- Breadcrumb end -->

						</div>
						<!-- App Hero header ends -->

						<!-- App body starts -->
						<div class="app-body" id="cbody">

							<div class="row">
								<div class="col-sm-4 offset-sm-4">
									<div class="row">
										<div class="col-6">
											<div class="card mb-4 bg-success">
												<div class="card-body d-flex align-items-center ">
													<table class="w-100  text-center">
														<tr>
															<td>
																<span class="smallText text-white">Marked</span>
															</td>
														</tr>
														<tr>

															<td class="">
																<h2 class="m-0 text-white number " id="markedCount">0</h2>
															</td>
														</tr>
													</table>
												</div>

											</div>

										</div>
										<div class="col-6">
											<div class="card mb-4 backGroundRed">
												<div class="card-body d-flex align-items-center">
													<table class="w-100  text-center">
														<tr>
															<td>
																<span class="smallText text-white">Not Marked</span>
															</td>
														</tr>
														<tr>
															<td class="">
																<h2 class="m-0 text-black number text-white" id="notMarkedCount">0</h2>
															</td>
														</tr>

													</table>
												</div>

											</div>
										</div>
									</div>
								</div>
							</div>



							<div class="row">
								<div class="col-lg-3 col-sm-4 col-12">
									<div class="mb-3">
										<div class="row">
											<div class="col-12"><label class="form-label fs-6">Search By :</label></div>

										</div>


									</div>
								</div>
							</div>



							<!-- Row start -->
							<div class="row ">

								<div class="col-lg-3 col-sm-4 col-12 text-center">
									<div class="mb-3">
										<div class="row">
											<div class="col-3 text-end"><label class="form-label smallText">Name -</label></div>


											<div class="col-9">
												<select id="select-state" class="form-select removeCorner smallText" onchange="loadUserAttendanceHead(1)">
													<option value="0">All users</option>
													<?php
													$userResultAttendance = Database::operation("SELECT user.id,user.fname,user.lname,user.jid FROM `user` INNER JOIN `position` ON `user`.`position_id`=`position`.`id` INNER JOIN `department` ON `department`.`id`=`position`.`department_id` WHERE `department`.`name`='" . $admin["department"] . "' AND `user`.`user_status_id`='1'", "s");


													$userResultAttendanceNumbers = $userResultAttendance->num_rows;
													if ($userResultAttendanceNumbers != 0) {
														for ($typ = 0; $typ < $userResultAttendanceNumbers; $typ++) {
															$userselect = $userResultAttendance->fetch_assoc();

													?>
															<option value="<?php echo $userselect["id"] ?>"><?php echo $userselect["fname"] . " " . $userselect["lname"] . " " . $userselect["jid"] ?></option>
													<?php
														}
													}
													?>
												</select>
											</div>


										</div>




									</div>
								</div>

								<div class="col-lg-3 col-sm-4 col-12 text-center">
									<div class="mb-3">


										<div class="row">
											<div class="col-3 text-end"><label class="form-label smallText">Status</label></div>
											<div class="col-9">
												<select id="markStatus" class="form-select removeCorner smallText" onchange="loadUserAttendanceHead(1)">

													<option value="1" selected>All</option>
													<option value="2">Marked</option>

												</select>
											</div>

										</div>


									</div>
								</div>


								<div class="col-lg-3 col-sm-4 col-12 text-center">
									<div class="mb-3">


										<div class="row">
											<div class="col-3 text-end"><label class="form-label smallText">From Date -</label></div>
											<div class="col-9"><input type="date" id="from" class="form-control removeCorner smallText" placeholder="Search by first name" value="" oninput="loadUserAttendanceHead(1)" /></div>
										</div>


									</div>
								</div>

								<div class="col-lg-3 col-sm-4 col-12 text-center">
									<div class="">
										<div class="row">
											<div class="col-3 text-end"><label class="form-label smallText">To Date -</label></div>
											<div class="col-9"><input type="date" id="to" class="form-control removeCorner smallText" placeholder="Search by user position" oninput="loadUserAttendanceHead(1)" value="" /></div>
										</div>


									</div>
								</div>

								<div class="col-lg-3 col-sm-4 col-12 text-center">
									<div class="">
										<div class="row">
											<div class="col-3 text-end"><label class="form-label smallText">Order By</label></div>
											<div class="col-9">
												<div class="form-check">
													<input class="form-check-input" type="radio" name="btnradio" id="exampleRadios1" value="ASC" onchange="loadUserAttendanceHead(1)">
													<label class="form-check-label smallText" for="exampleRadios1">
														Date ASC
													</label>
												</div>
												<div class="form-check">
													<input class="form-check-input" type="radio" name="btnradio" id="exampleRadios2" value="DESC" checked onchange="loadUserAttendanceHead(1)">
													<label class="form-check-label smallText text-start" for="exampleRadios2">
														Date DESC
													</label>
												</div>
											</div>
										</div>


									</div>
								</div>



								<div class="col-12 text-center">
									<div class="mb-3">



										<div class="row">
											<div class="col-12 text-end">
												<button class="btn btn-danger removeCorner" onclick="clearSearchDataAttendance()"><i class="bi bi-x"></i></button>
											</div>
										</div>


									</div>
								</div>

							</div>

							<div class="col-xxl-12">
								<div class="card mb-4">
									<div class="card-body">
										<div class="row">

											<div class="table-responsive">
												<table class="table align-middle table-hover m-0">
													<thead>
														<tr>
															<th scope="col">No</th>
															<th scope="col">Id</th>
															<th scope="col">Name</th>
															<th scope="col">Email</th>
															<th scope="col">Date</th>
															<th scope="col">Attendance Status</th>

														</tr>
													</thead>
													<tbody id="tableBodyUser">

													</tbody>
												</table>
											</div>
										</div>
										<div class="row mt-3">
											<div class="col-12 text-center">
												<!-- Card start -->
												<div class="card mb-4">
													<div class="card-body">
														<div class="btn-group" role="group" aria-label="Basic checkbox toggle button group" id="pagicontainer">

														</div>
													</div>
												</div>
												<!-- Card end -->
											</div>
										</div>
									</div>
								</div>

							</div>


							<!-- Row end -->

						</div>
						<!-- App body ends -->

						<!-- App footer start -->
						<div class="app-footer">
							<span>© 2024 Jadetimes Media LLC. All rights reserved.</span>
						</div>
						<!-- App footer end -->

					</div>
					<!-- App container ends -->

				</div>
				<!-- Main container end -->

			</div>
			<!-- Page wrapper end -->

			<!-- *************
			************ JavaScript Files *************
		************* -->
			<!-- Required jQuery first, then Bootstrap Bundle JS -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/bootstrap.bundle.min.js"></script>

			<!-- *************
			************ Vendor Js Files *************
		************* -->

			<!-- Overlay Scroll JS -->
			<script src="assets/vendor/overlay-scroll/jquery.overlayScrollbars.min.js"></script>
			<script src="assets/vendor/overlay-scroll/custom-scrollbar.js"></script>

			<!-- Custom JS files -->
			<script src="assets/js/custom.js"></script>


			<!-- Bootstrap JS and dependencies -->
			<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
			<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
			<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
			<script src="assets/js/user.js"></script>


			<!-- Custom JS -->

		</body>

		</html>
	<?php
	}
} else {
	?>
	<script>
		window.location = "userLogin.php";
	</script>
<?php
}
?>