<?php
session_start();
require "connection.php";
if (isset($_SESSION["jd_admin"])) {

	$admin = $_SESSION["jd_admin"];

	$autoGeneratedPassword = uniqid() . $admin["id"];

	$d = new DateTime();
	$tz = new DateTimeZone("Asia/Colombo");
	$d->setTimezone($tz);
	$today = $d->format("Y-m-d");

?>

	<!DOCTYPE html>
	<html lang="en">

	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<title>Jade Times - Manage Articles / admin</title>

		<!-- Meta -->
		<meta name="description" content="Marketplace for Bootstrap Admin Dashboards" />
		<meta name="author" content="Bootstrap Gallery" />
		<link rel="canonical" href="https://www.bootstrap.gallery/">
		<meta property="og:url" content="https://www.bootstrap.gallery">
		<meta property="og:title" content="Admin Templates - Dashboard Templates | Bootstrap Gallery">
		<meta property="og:description" content="Marketplace for Bootstrap Admin Dashboards">
		<meta property="og:type" content="Website">
		<meta property="og:site_name" content="Bootstrap Gallery">
		<link rel="icon" href="assets/img/iconImg.jpg" />

		<!-- *************
			************ CSS Files *************
		************* -->
		<link rel="stylesheet" href="assets/fonts/bootstrap/bootstrap-icons.css" />
		<link rel="stylesheet" href="assets/css/main.css" />

		<!-- *************
			************ Vendor Css Files *************
		************ -->

		<!-- Scrollbar CSS -->
		<link rel="stylesheet" href="assets/vendor/overlay-scroll/OverlayScrollbars.min.css" />
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/css/selectize.bootstrap3.min.css" integrity="sha256-ze/OEYGcFbPRmvCnrSeKbRTtjG4vGLHXgOqsyLFTRjg=" crossorigin="anonymous" />
		<link rel="stylesheet" href="assets/css/admin.css" />
	</head>

	<body class="backgroundColorChange" onload="loadUserArticles(0)">

		<!-- Page wrapper start -->
		<div class="page-wrapper">

			<!-- Main container start -->
			<div class="main-container">
				<?php
				require "adminSideBar.php";
				?>

				<!-- App container starts -->
				<div class="app-container">
					<!-- App header starts -->
					<?php

					require "adminAppHeader.php";
					?>
					<!-- App header ends -->

					<!-- App hero header starts -->
					<div class="app-hero-header d-flex align-items-start">

						<!-- Breadcrumb start -->
						<ol class="breadcrumb d-none d-lg-flex align-items-center">
							<li class="breadcrumb-item">
								<i class="bi bi-house text-dark"></i>
								<a href="adminPanel.php">Home</a>
							</li>
							<li class="breadcrumb-item" aria-current="page">Manage Articles</li>
						</ol>
						<!-- Breadcrumb end -->

					</div>
					<!-- App Hero header ends -->

					<!-- App body starts -->
					<div class="app-body" id="cbody">
						<?php

						$userResultAttendance = Database::operation("SELECT * FROM `user`  WHERE `type_id` IN ('5','1','4')", "s");
						$addNewList = $userResultAttendance;
						?>


						<div class="row mb-5">
							<div class="col-12">
								<p class="d-inline-flex gap-1">

									<button class="btn btn-dark backgroundColorChange removeCorner" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
										<i class="bi bi-journal-plus"></i> Add New Article
									</button>
								</p>
								<div class="collapse" id="collapseExample">
									<div class="card card-body">

										<div class="row">
											<div class="col-xxl-12">
												<div class="card mb-4">

													<div class="card-body">
														<!-- Row start -->
														<div class="row">
															<div class="col-xxl-12">
																<div class="card mb-4">
																	<div class="card-header">
																		<h5 class="card-title">Add Article</h5>
																	</div>
																	<div class="card-body">

																		<!-- Row start -->
																		<div class="row" aria-disabled="">
																			<div class="col-12 alert alert-danger d-none" id="infoMessage" role="alert">
																			</div>



																			<div class="col-lg-6 col-sm-12 col-12">
																				<div class="mb-3">
																					<label class="form-label">Writer</label><label class="colorRed ms-3 fs-6">*</label>
																					<select class="form-select removeCorner" id="writerId">
																						<option value="0">Select writer</option>
																						<?php
																						if ($addNewList->num_rows != 0) {
																							for ($adi = 0; $adi < $addNewList->num_rows; $adi++) {
																								$userselect = $addNewList->fetch_assoc();

																						?>
																								<option value="<?php echo $userselect["id"] ?>"><?php echo $userselect["fname"] . " " . $userselect["lname"] . " " . $userselect["jid"] ?></option>
																						<?php
																							}
																						}

																						?>
																					</select>
																				</div>
																				<div class="mb-3">
																					<label class="form-label">Date</label>
																					<input type="date" class="form-control removeCorner" id="date" placeholder="Enter Date" />
																				</div>

																				<div class="mb-3">
																					<label class="form-label">Article Type</label>
																					<select id="articleType" class="form-control removeCorner">
																						<option value="0">Select</option>
																						<option value="1">Commercial</option>
																						<option value="2">Non Commercial</option>
																					</select>
																				</div>
																			</div>


																			<div class="col-sm-6 col-12">
																				<div class="mb-3">
																					<label class="form-label">Article Title </label>
																					<textarea class="form-control removeCorner" id="title" placeholder="Article title" rows="5"></textarea>
																				</div>
																			</div>
																		</div>
																		<!-- Row end -->
																	</div>
																	<div class="card-footer">
																		<div class="d-flex gap-2 justify-content-center">
																			<button type="button" onclick="addNewArticleAdmin()" class="btn btn-dark backgroundColorChange w-50 removeCorner">
																				Add Article
																			</button>
																		</div>
																	</div>
																</div>
															</div>
														</div>
														<!-- Row end -->
													</div>


												</div>
												<!-- Row end -->
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>

						<div class="row">
							<div class="col-lg-3 col-sm-4 col-12">
								<div class="mb-3">
									<div class="row">
										<div class="col-12"><label class="form-label fs-6">Search By :</label></div>

									</div>


								</div>
							</div>
						</div>



						<!-- Row start -->
						<div class="row ">

							<div class="col-lg-3 col-sm-4 col-12 text-center">
								<div class="mb-3">
									<div class="row">
										<div class="col-3 text-end"><label class="form-label smallText">Name -</label></div>


										<div class="col-9">
											<select id="select-state" class="form-select removeCorner smallText" onchange="loadUserArticles(1)">
												<option value="0">All users</option>
												<?php



												$userResultAttendance = Database::operation("SELECT * FROM `user` WHERE `type_id` IN ('5','1','4')", "s");
												$userResultAttendanceNumbers = $userResultAttendance->num_rows;
												if ($userResultAttendanceNumbers != 0) {
													for ($typ = 0; $typ < $userResultAttendanceNumbers; $typ++) {
														$userselect = $userResultAttendance->fetch_assoc();

												?>
														<option value="<?php echo $userselect["id"] ?>"><?php echo $userselect["fname"] . " " . $userselect["lname"] . " " . $userselect["jid"] ?></option>
												<?php
													}
												}
												?>
											</select>
										</div>


									</div>




								</div>
							</div>



							<div class="col-lg-3 col-sm-4 col-12 text-center">
								<div class="mb-3">


									<div class="row">
										<div class="col-3 text-end"><label class="form-label smallText">From Date -</label></div>
										<div class="col-9"><input type="date" id="from" class="form-control removeCorner smallText" placeholder="Search by first name" value="" oninput="loadUserArticles(1)" /></div>
									</div>


								</div>
							</div>

							<div class="col-lg-3 col-sm-4 col-12 text-center">
								<div class="">
									<div class="row">
										<div class="col-3 text-end"><label class="form-label smallText">To Date -</label></div>
										<div class="col-9"><input type="date" id="to" class="form-control removeCorner smallText" placeholder="Search by user position" oninput="loadUserArticles(1)" value="" /></div>
									</div>


								</div>
							</div>

							<div class="col-lg-3 col-sm-4 col-12 text-center mt-lg-0 mt-3">
								<div class="">
									<div class="row">
										<div class="col-3 text-end"><label class="form-label smallText">Order By</label></div>
										<div class="col-9">
											<div class="form-check">
												<input class="form-check-input" type="radio" name="btnradio" id="exampleRadios1" value="ASC" onchange="loadUserArticles(1)">
												<label class="form-check-label smallText" for="exampleRadios1">
													Date ASC
												</label>
											</div>
											<div class="form-check">
												<input class="form-check-input" type="radio" name="btnradio" id="exampleRadios2" value="DESC" checked onchange="loadUserArticles(1)">
												<label class="form-check-label smallText text-start" for="exampleRadios2">
													Date DESC
												</label>
											</div>
										</div>
									</div>


								</div>
							</div>
							<div class="col-lg-6 col-12 text-center mt-lg-0 mt-3">
								<div class="mb-3">
									<div class="row">
										<div class="col-3 text-end"><label class="form-label smallText">Type -</label></div>


										<div class="col-9">
											<select id="status" class="form-select removeCorner smallText" onchange="loadUserArticles(1)">
												<option value="0">All</option>
												<option value="1">Commercial</option>
												<option value="2">None Commercial</option>

											</select>
										</div>


									</div>




								</div>
							</div>



							<div class="col-12 col-lg-6 text-center">
								<div class="mb-3">



									<div class="row">
										<div class="col-12 text-lg-start text-end">
											<button class="btn btn-danger removeCorner" onclick="window.location='manageArticles.php'"><i class="bi bi-x"></i></button>
										</div>
									</div>


								</div>
							</div>

						</div>

						<div class="col-xxl-12">
							<div class="card mb-4">
								<div class="card-body">
									<div class="row">

										<div class="table-responsive">
											<table class="table align-middle table-hover m-0">
												<thead>
													<tr>
														<th scope="col">No</th>
														<th scope="col">Id</th>
														<th scope="col">Name</th>

														<th scope="col" class="w-25">Title</th>
														<th scope="col">Date</th>
														<th scope="col">Submit Date</th>
														<th scope="col">Type</th>

													</tr>
												</thead>
												<tbody id="tableBodyUser">

												</tbody>
											</table>
										</div>
									</div>
									<div class="row mt-3">
										<div class="col-12 text-center">
											<!-- Card start -->
											<div class="card mb-4">
												<div class="card-body">
													<div class="btn-group" role="group" aria-label="Basic checkbox toggle button group" id="pagicontainer">

													</div>
												</div>
											</div>
											<!-- Card end -->
										</div>
									</div>
								</div>
							</div>

						</div>
						<!-- Row end -->

					</div>
					<!-- App body ends -->

					<!-- App footer start -->
					<div class="app-footer">
						<span>© 2024 Jadetimes Media LLC. All rights reserved.</span>
					</div>
					<!-- App footer end -->

				</div>
				<!-- App container ends -->

			</div>
			<!-- Main container end -->

		</div>
		<!-- Page wrapper end -->

		<!-- *************
			************ JavaScript Files *************
		************* -->
		<!-- Required jQuery first, then Bootstrap Bundle JS -->
		<script src="assets/js/jquery.min.js"></script>
		<script src="assets/js/bootstrap.bundle.min.js"></script>

		<!-- *************
			************ Vendor Js Files *************
		************* -->

		<!-- Overlay Scroll JS -->
		<script src="assets/vendor/overlay-scroll/jquery.overlayScrollbars.min.js"></script>
		<script src="assets/vendor/overlay-scroll/custom-scrollbar.js"></script>

		<!-- Custom JS files -->
		<script src="assets/js/custom.js"></script>

		<script src="assets/js/admin.js"></script>
		<!-- Bootstrap JS and dependencies -->
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


		<!-- Custom JS -->
		<script>
			function addNewArticleAdmin() {
				var msg = document.getElementById("infoMessage");
				var title = document.getElementById("title");
				var writerId = document.getElementById("writerId");
				var date = document.getElementById("date");
				var articleType = document.getElementById("articleType");


				if (writerId.value == 0) {
					msg.innerHTML = "Please Select A Writer";
					msg.classList = "alert alert-danger";
				} else if (!date.value) {

					msg.innerHTML = "Please Select A Date";
					msg.classList = "alert alert-danger";

				} else if (articleType.value == 0) {

					msg.innerHTML = "Please select an Article Type";
					msg.classList = "alert alert-danger";

				} else if (!title.value) {

					msg.innerHTML = "Title  is Empty";
					msg.classList = "alert alert-danger";

				} else {

					var formData = new FormData();
					formData.append("title", title.value);
					formData.append("writer", writerId.value);
					formData.append("date", date.value);
					formData.append("articleType", articleType.value);

					fetch(baseUrl + "adminArticleSubmittProcess.php", {
							method: "POST",
							body: formData,

						})
						.then(function(resp) {

							try {
								let response = resp.json();
								return response;
							} catch (error) {
								msg.classList = "alert alert-danger";
								msg.innerHTML = "Something wrong please try again";
								emailField.classList = "form-control";
								passwordField.classList = "form-control";
							}

						})
						.then(function(value) {

							if (value.type == "error") {
								msg.classList = "alert alert-danger";
								msg.innerHTML = value.message;

							} else if (value.type == "success") {
								msg.classList = "alert alert-success";
								msg.innerHTML = value.message;

								setTimeout(() => {
									window.location = "manageArticles.php";
								}, 1000);
							} else {
								msg.classList = "alert alert-danger";
								msg.innerHTML = "Something wrong please try again";
								emailField.classList = "form-control";
								passwordField.classList = "form-control";
							}

						})
						.catch(function(error) {
							console.log(error);
						});


				}
			}
		</script>

	</body>

	</html>
<?php

} else {
?>
	<script>
		window.location = "adminLogin.php"
	</script>
<?php
}
?>