<?php
session_start();
require "connection.php";
if (isset($_SESSION["jd_admin"])) {

	$admin = $_SESSION["jd_admin"];
	$autoGeneratedPassword = uniqid() . $admin["id"];

	$d = new DateTime();
	$tz = new DateTimeZone("Asia/Colombo");
	$d->setTimezone($tz);
	$today = $d->format("Y-m-d");

?>

	<!DOCTYPE html>
	<html lang="en">

	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<title>Jade Times - Manage Users add /edit</title>

		<!-- Meta -->
		<meta name="description" content="Marketplace for Bootstrap Admin Dashboards" />
		<meta name="author" content="Bootstrap Gallery" />
		<link rel="canonical" href="https://www.bootstrap.gallery/">
		<meta property="og:url" content="https://www.bootstrap.gallery">
		<meta property="og:title" content="Admin Templates - Dashboard Templates | Bootstrap Gallery">
		<meta property="og:description" content="Marketplace for Bootstrap Admin Dashboards">
		<meta property="og:type" content="Website">
		<meta property="og:site_name" content="Bootstrap Gallery">
		<link rel="icon" href="assets/img/iconImg.jpg" />

		<!-- *************
			************ CSS Files *************
		************* -->
		<link rel="stylesheet" href="assets/fonts/bootstrap/bootstrap-icons.css" />
		<link rel="stylesheet" href="assets/css/main.css" />

		<!-- *************
			************ Vendor Css Files *************
		************ -->

		<!-- Scrollbar CSS -->
		<link rel="stylesheet" href="assets/vendor/overlay-scroll/OverlayScrollbars.min.css" />
		<link rel="stylesheet" href="assets/css/admin.css" />
	</head>

	<body class="backgroundColorChange" onload="loadUserDateToFront(0)">

		<!-- Page wrapper start -->
		<div class="page-wrapper">

			<!-- Main container start -->
			<div class="main-container">
				<?php require "adminSideBar.php" ?>


				<!-- App container starts -->
				<div class="app-container">

					<!-- App header starts -->
					<?php require "adminAppHeader.php" ?>
					<!-- App header ends -->

					<!-- App hero header starts -->
					<div class="app-hero-header d-flex align-items-start">

						<!-- Breadcrumb start -->
						<ol class="breadcrumb d-none d-lg-flex align-items-center">
							<li class="breadcrumb-item">
								<i class="bi bi-house text-dark"></i>
								<a href="adminPanel.php">Home</a>
							</li>
							<li class="breadcrumb-item" aria-current="page">Manage User</li>
						</ol>
						<!-- Breadcrumb end -->

					</div>
					<!-- App Hero header ends -->

					<!-- App body starts -->
					<div class="app-body" id="cbody">
						<div class="row mb-5">
							<div class="col-12">
								<p class="d-inline-flex gap-1">

									<button class="btn btn-dark backgroundColorChange removeCorner" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
										<i class="bi bi-person-plus"></i> Add New User
									</button>
								</p>
								<div class="collapse" id="collapseExample">
									<div class="card card-body">

										<div class="row">
											<div class="col-xxl-12">
												<div class="card mb-4">

													<div class="card-body">
														<!-- Row start -->
														<div class="row">
															<div class="col-12 mb-3">
																<div class="alert alert-danger d-none" id="infoMessageProfileUpdate" role="alert">
																</div>
															</div>
															<div class="col-12 text-center mb-3">

															</div>

															<div class="col-lg-3 col-sm-4 col-12">
																<div class="mb-3">
																	<label class="form-label">Surname</label>
																	<input type="text" id="sname" class="form-control removeCorner" value="" placeholder="Enter Surname" />
																</div>
															</div>
															<div class="col-lg-3 col-sm-4 col-12">
																<div class="mb-3">
																	<label class="form-label ">First Name</label><label class="colorRed ms-1 fs-6">*</label>
																	<input type="text" id="fname" class="form-control removeCorner" placeholder="Enter First Name" value="" />
																</div>
															</div>
															<div class="col-lg-3 col-sm-4 col-12">
																<div class="mb-3">
																	<label class="form-label">Middle Name</label>
																	<input type="text" id="mname" class="form-control removeCorner" placeholder="Enter Middle Name" value="" />
																</div>
															</div>
															<div class="col-lg-3 col-sm-4 col-12">
																<div class="mb-3">
																	<label class="form-label">Last Name</label><label class="colorRed ms-1 fs-6">*</label>
																	<input type="text" id="lname" class="form-control removeCorner" placeholder="Enter Last Name" value="" />
																</div>
															</div>

															<div class="col-12">
																<hr>
															</div>
															<div class="col-lg-3 col-sm-4 col-12">
																<div class="mb-3">
																	<label class="form-label">Jade Times ID</label><label class="colorRed ms-1 fs-6">*</label>
																	<input type="text" id="jtid" class="form-control removeCorner" placeholder="Jade Times Id" value="" />
																</div>
															</div>

															<?php

															if ($admin["user_type"] == "superAdmin") {
															?>
																<div class="col-lg-3 col-sm-4 col-12">
																	<div class="mb-3">
																		<label class="form-label">User Type</label><label class="colorRed ms-1 fs-6">*</label>
																		<select class="form-select removeCorner" id="type">
																			<option value="0">Select</option>

																			<?php



																			$userTypeResult = Database::operation("SELECT * FROM `type`", "s");
																			$unum = $userTypeResult->num_rows;
																			if ($unum != 0) {
																				for ($i = 0; $i < $unum; $i++) {

																					$type = $userTypeResult->fetch_assoc();
																					$typeId = $type["id"];
																			?>
																					<option value="<?php echo $typeId ?>"><?php echo $type["name"] ?></option>
																			<?php
																				}
																			}
																			?>

																		</select>
																	</div>
																</div>
															<?php
															}

															?>
															<div class="col-lg-3 col-sm-4 col-12">
																<div class="mb-3">
																	<label class="form-label">Email</label><label class="colorRed ms-1 fs-6">*</label>
																	<input type="email" id="email" class="form-control removeCorner" placeholder="Enter email address" value="" />
																</div>
															</div>
															<div class="col-lg-3 col-sm-4 col-12">
																<div class="mb-3">
																	<label class="form-label">Phone</label>
																	<input type="text" id="mobile" class="form-control removeCorner" placeholder="Enter phone number" value="" />
																</div>
															</div>

															<div class="col-lg-3 col-sm-4 col-12">
																<div class="mb-3">
																	<label class="form-label">NIC No/Passport No/Driving License No</label>
																	<input type="text" id="nic" class="form-control removeCorner" placeholder="national ID" value="" />
																</div>
															</div>
															<div class="col-lg-3 col-sm-4 col-12">
																<div class="mb-3">
																	<label class="form-label">Date Of Birth</label>
																	<input type="date" id="dob" class="form-control removeCorner" placeholder="date of birth" value="" />
																</div>
															</div>
															<div class="col-lg-3 col-sm-4 col-12">
																<div class="mb-3">
																	<label class="form-label">Gender</label>
																	<select class="form-select removeCorner" id="gender">
																		<option value="0">Select</option>

																		<?php



																		$genderResult = Database::operation("SELECT * FROM `gender`", "s");
																		$gnum = $genderResult->num_rows;
																		if ($gnum != 0) {
																			for ($i = 0; $i < $gnum; $i++) {
																				$genders = $genderResult->fetch_assoc();
																				$genderId = $genders["id"];
																		?>
																				<option value="<?php echo $genderId ?>"><?php echo $genders["name"] ?></option>
																		<?php
																			}
																		}
																		?>

																	</select>
																</div>
															</div>


															<div class="col-12">
																<hr>

															</div>
															<div class="col-lg-3 col-sm-4 col-12">
																<div class="mb-3">
																	<label class="form-label">Registred Date</label><label class="colorRed ms-1 fs-6">*</label>
																	<input type="date" id="regDate" class="form-control removeCorner" placeholder="registred date" value="<?php echo $today ?>" />
																</div>
															</div>
															<div class="col-lg-3 col-sm-4 col-12">
																<div class="mb-3">
																	<label class="form-label">Department</label><label class="colorRed ms-1 fs-6">*</label>

																	<select class="form-select removeCorner" id="department" onchange="getThePositionForDepartment()">
																		<option value="0">Select</option>

																		<?php



																		$departResult = Database::operation("SELECT * FROM `department`", "s");
																		$dnum = $departResult->num_rows;
																		if ($departResult != 0) {
																			for ($h = 0; $h < $dnum; $h++) {
																				$department = $departResult->fetch_assoc();
																				$departmentID = $department["id"];
																		?>
																				<option value="<?php echo $departmentID ?>"><?php echo $department["name"] ?></option>
																		<?php
																			}
																		}
																		?>

																	</select>


																</div>
															</div>

															<div class="col-lg-3 col-sm-4 col-12">
																<div class="mb-3">
																	<label class="form-label">Position</label><label class="colorRed ms-1 fs-6">*</label>
																	<select class="form-select removeCorner" id="position">

																	</select>


																</div>
															</div>
															<div class="col-lg-3 col-sm-4 col-12">
																<div class="mb-3">
																	<label class="form-label">Duration</label>
																	<input type="text" id="duration" class="form-control removeCorner" placeholder="duration" />
																</div>
															</div>

															<div class="col-12">
																<hr>
															</div>
															<div class="col-lg-3 col-sm-4 col-12">
																<div class="mb-3">
																	<label class="form-label">Linkdin Profile</label>
																	<input type="text" id="linkdin" class="form-control removeCorner" placeholder="profileUrl" />
																</div>
															</div>
															<div class="col-12">
																<hr>
																<label class="form-label mt-2 fs-6">Address</label>
															</div>

															<div class="col-lg-3 col-sm-4 col-12">
																<div class="mb-3">
																	<label class="form-label">No</label>
																	<input type="text" id="no" class="form-control removeCorner" placeholder="Enter no" />
																</div>
															</div>

															<div class="col-lg-3 col-sm-4 col-12">
																<div class="mb-3">
																	<label class="form-label">Line 1</label><label class="colorRed ms-1 fs-6">*</label>
																	<input type="text" id="line1" class="form-control removeCorner" placeholder="Enter Line 1" />
																</div>
															</div>

															<div class="col-lg-3 col-sm-4 col-12">
																<div class="mb-3">
																	<label class="form-label">Line 2</label>
																	<input type="text" id="line2" class="form-control removeCorner" placeholder="Enter Line 2" />
																</div>
															</div>
															<div class="col-lg-3 col-sm-4 col-12">
																<div class="mb-3">
																	<label class="form-label">City</label><label class="colorRed ms-1 fs-6">*</label>
																	<input type="text" id="city" class="form-control removeCorner" placeholder="Enter city" />
																</div>
															</div>


															<div class="col-lg-3 col-sm-4 col-12">
																<div class="mb-3">
																	<label class="form-label">Select Country</label><label class="colorRed ms-1 fs-6">*</label>
																	<select class="form-select removeCorner" id="country">
																		<option value="0">Select</option>

																		<?php



																		$citiesResult = Database::operation("SELECT * FROM `country`", "s");
																		$num = $citiesResult->num_rows;
																		if ($num != 0) {
																			for ($i = 0; $i < $num; $i++) {
																				$city = $citiesResult->fetch_assoc();
																				$cityId = $city["id"];
																		?>
																				<option value="<?php echo $cityId ?>"><?php echo $city["name"] ?></option>
																		<?php
																			}
																		}
																		?>

																	</select>
																</div>
															</div>


															<div class="col-12">
																<hr>

															</div>

															<div class="col-lg-3 col-sm-4 col-12">
																<div class="mb-3">
																	<label class="form-label">Password</label><label class="colorRed ms-1 fs-6">*</label>
																	<input type="text" id="password" class="form-control removeCorner" disabled placeholder="password" value="<?php echo $autoGeneratedPassword; ?>" />
																</div>
															</div>



														</div>
														<!-- Row end -->
													</div>
													<div class="col-12 mt-4">
														<div class="d-flex gap-2 justify-content-center">

															<button type="button" onclick="registerNewUser('<?php echo $admin['user_type'] ?>')" class="btn btn-dark removeCorner backgroundColorChange w-50">
																Register New User
															</button>
														</div>
													</div>

												</div>
												<!-- Row end -->
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-3 col-sm-4 col-12">
								<div class="mb-3">
									<div class="row">
										<div class="col-12"><label class="form-label fs-6">Search By :</label></div>

									</div>


								</div>
							</div>
						</div>



						<!-- Row start -->
						<div class="row ">

							<div class="col-lg-3 col-sm-4 col-12 text-center">
								<div class="mb-3">
									<div class="row">
										<div class="col-3 text-end"><label class="form-label smallText">Name -</label></div>
										<div class="col-9"><input type="text" id="searchname" class="form-control removeCorner smallText" placeholder="Search by first name" oninput="loadUserDateToFront(1)" /></div>
									</div>




								</div>
							</div>

							<div class="col-lg-3 col-sm-4 col-12 text-center">
								<div class="mb-3">


									<div class="row">
										<div class="col-3 text-end"><label class="form-label smallText">email -</label></div>
										<div class="col-9"><input type="text" id="searchemail" class="form-control removeCorner smallText" placeholder="Search by first name" value="" oninput="loadUserDateToFront(1)" /></div>
									</div>


								</div>
							</div>
							<div class="col-lg-3 col-sm-4 col-12 text-center">
								<div class="">
									<div class="row">
										<div class="col-3 text-end"><label class="form-label smallText">ID -</label></div>
										<div class="col-9"><input type="text" id="searchid" class="form-control removeCorner smallText" placeholder="Search by Jade Times ID" value="" oninput="loadUserDateToFront(1)" /></div>
									</div>


								</div>
							</div>
							<div class="col-lg-3 col-sm-4 col-12 text-center">
								<div class="">
									<div class="row">
										<div class="col-3 text-end"><label class="form-label smallText">Position -</label></div>
										<div class="col-9"><input type="text" id="searchposition" class="form-control removeCorner smallText" placeholder="Search by user position" oninput="loadUserDateToFront(1)" value="" /></div>
									</div>


								</div>
							</div>
							<div class="col-lg-3 col-sm-4 col-12 text-center">
								<div class="mb-3">
									<div class="row">
										<div class="col-3 text-end"><label class="form-label smallText">Type -</label></div>
										<div class="col-9">

											<select class="form-select removeCorner smallText" id="searchtype" onchange="loadUserDateToFront(1)">
												<option value="0" selected>All</option>

												<?php



												$typeResultListForSearch = Database::operation("SELECT * FROM `type`", "s");
												$typeResultListForSearchNumbers = $typeResultListForSearch->num_rows;
												if ($typeResultListForSearchNumbers != 0) {
													for ($typ = 0; $typ < $typeResultListForSearchNumbers; $typ++) {
														$typeSrh = $typeResultListForSearch->fetch_assoc();

												?>
														<option value="<?php echo $typeSrh["id"] ?>"><?php echo $typeSrh["name"] ?></option>
												<?php
													}
												}
												?>

											</select>
										</div>


									</div>






								</div>
							</div>

							<div class="col-lg-3 col-sm-4 col-12 text-center">
								<div class="mb-3">


									<div class="row">
										<div class="col-3 text-end"><label class="form-label smallText">Status -</label></div>

										<div class="col-9">

											<select class="form-select removeCorner smallText" id="searchstatus" onchange="loadUserDateToFront(1)">
												<option value="0" selected>All</option>

												<?php



												$statusResultListForSearch = Database::operation("SELECT * FROM `user_status`", "s");
												$statusResultListForSearchNumbers = $statusResultListForSearch->num_rows;
												if ($statusResultListForSearchNumbers != 0) {
													for ($sty = 0; $sty < $statusResultListForSearchNumbers; $sty++) {
														$statusSrh = $statusResultListForSearch->fetch_assoc();

												?>
														<option value="<?php echo $statusSrh["id"] ?>" <?php if ($statusSrh["name"] == "ACTIVE") {
																										?>selected <?php
																												} ?>><?php echo $statusSrh["name"] ?></option>
												<?php
													}
												}
												?>

											</select>
										</div>

									</div>


								</div>
							</div>
							<div class="col-lg-3 col-sm-4 col-12 text-center">
								<div class="mb-3">



									<div class="row">
										<div class="col-12 text-start">
											<button class="btn btn-danger removeCorner" onclick="clearSearchData()"><i class="bi bi-x"></i></button>
										</div>
									</div>


								</div>
							</div>

						</div>

						<div class="col-xxl-12">
							<div class="card mb-4">
								<div class="card-body">
									<div class="row">
										<div class="col-12 justify-content-center">

											<div class="container mt-5">
												<div class="horizontal-scroll-menu-container">
													<label class="btn btn-outline-info removeCorner" id="scroll-left">&#8672;</label>

													<div class="horizontal-scroll-menu" id="scroll-menu">
														<div class="card removeCorner">
															<div class="card-body removeCorner">
																<div class="btn-group" role="group" aria-label="Basic checkbox toggle button group">
																	<input type="radio" class="btn-check" id="depAll" name="btnradio" checked="" value="0" onchange='loadUserDateToFront(1)' />
																	<label class="btn btn-outline-info removeCorner" for="depAll">All</label>
																	<?php

																	$departmentResult = Database::operation("SELECT * FROM `department`", "s");
																	if ($departmentResult->num_rows != 0) {

																		for ($i = 0; $i < $departmentResult->num_rows; $i++) {
																			$departmenData = $departmentResult->fetch_assoc();
																	?>
																			<input type="radio" class="btn-check removeCorner" name="btnradio" value='<?php echo $departmenData["id"] ?>' id="dep<?php echo $i ?>" onchange="loadUserDateToFront(1)" />
																			<label class="btn btn-outline-info removeCorner" for="dep<?php echo $i ?>"><?php echo $departmenData["name"] ?></label>

																	<?php
																		}
																	}
																	?>




																</div>
															</div>
														</div>
													</div>
													<span class="btn btn-outline-info removeCorner removeCorner" id="scroll-right">&#8674;</span>
												</div>
												<!-- Card start -->

												<!-- Card end -->
											</div>
										</div>
										<div class="table-responsive">
											<table class="table align-middle table-hover m-0">
												<thead>
													<tr>
														<th scope="col">NO</th>
														<th scope="col">Id</th>
														<th scope="col">Name</th>
														<th scope="col">Email</th>
														<th scope="col">Mobile</th>
														<th scope="col">Department</th>
														<th scope="col">Position</th>
														<th scope="col">Registered date</th>
														<th scope="col">User Type</th>
														<th scope="col">Duration</th>
														<th scope="col">Status</th>

													</tr>
												</thead>
												<tbody id="tableBodyUser">

												</tbody>
											</table>
										</div>
									</div>
									<div class="row mt-3">
										<div class="col-12 text-center">
											<!-- Card start -->
											<div class="card mb-4">
												<div class="card-body">
													<div class="btn-group" role="group" aria-label="Basic checkbox toggle button group" id="pagicontainer">

													</div>
												</div>
											</div>
											<!-- Card end -->
										</div>
									</div>
								</div>
							</div>

						</div>
						<!-- Row end -->

					</div>
					<!-- App body ends -->

					<!-- App footer start -->
					<div class="app-footer">
						<span>© 2024 Jadetimes Media LLC. All rights reserved.</span>
					</div>
					<!-- App footer end -->

				</div>
				<!-- App container ends -->

			</div>
			<!-- Main container end -->

		</div>
		<!-- Page wrapper end -->

		<!-- *************
			************ JavaScript Files *************
		************* -->
		<!-- Required jQuery first, then Bootstrap Bundle JS -->
		<script src="assets/js/jquery.min.js"></script>
		<script src="assets/js/bootstrap.bundle.min.js"></script>

		<!-- *************
			************ Vendor Js Files *************
		************* -->

		<!-- Overlay Scroll JS -->
		<script src="assets/vendor/overlay-scroll/jquery.overlayScrollbars.min.js"></script>
		<script src="assets/vendor/overlay-scroll/custom-scrollbar.js"></script>

		<!-- Custom JS files -->
		<script src="assets/js/custom.js"></script>

		<script src="assets/js/admin.js"></script>
		<!-- Bootstrap JS and dependencies -->
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
		<!-- Custom JS -->
		<script>
			document.addEventListener('DOMContentLoaded', function() {
				const scrollMenu = document.getElementById('scroll-menu');
				const scrollLeft = document.getElementById('scroll-left');
				const scrollRight = document.getElementById('scroll-right');

				scrollLeft.addEventListener('click', function() {
					scrollMenu.scrollBy({
						left: -200,
						behavior: 'smooth'
					});
				});

				scrollRight.addEventListener('click', function() {
					scrollMenu.scrollBy({
						left: 200,
						behavior: 'smooth'
					});
				});
			});
		</script>
	</body>

	</html>
<?php

} else {
?>
	<script>
		window.location = "adminLogin.php"
	</script>
<?php
}
?>