<?php
session_start();
require "connection.php";
if (isset($_SESSION["jd_admin"])) {

	$admin = $_SESSION["jd_admin"];

	$autoGeneratedPassword = uniqid() . $admin["id"];

	$d = new DateTime();
	$tz = new DateTimeZone("Asia/Colombo");
	$d->setTimezone($tz);
	$today = $d->format("Y-m-d");

?>

	<!DOCTYPE html>
	<html lang="en">

	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<title>Jade Times - Manage Articles / admin</title>

		<!-- Meta -->
		<meta name="description" content="Marketplace for Bootstrap Admin Dashboards" />
		<meta name="author" content="Bootstrap Gallery" />
		<link rel="canonical" href="https://www.bootstrap.gallery/">
		<meta property="og:url" content="https://www.bootstrap.gallery">
		<meta property="og:title" content="Admin Templates - Dashboard Templates | Bootstrap Gallery">
		<meta property="og:description" content="Marketplace for Bootstrap Admin Dashboards">
		<meta property="og:type" content="Website">
		<meta property="og:site_name" content="Bootstrap Gallery">
		<link rel="icon" href="assets/img/iconImg.jpg" />

		<!-- *************
			************ CSS Files *************
		************* -->
		<link rel="stylesheet" href="assets/fonts/bootstrap/bootstrap-icons.css" />
		<link rel="stylesheet" href="assets/css/main.css" />

		<!-- *************
			************ Vendor Css Files *************
		************ -->

		<!-- Scrollbar CSS -->
		<link rel="stylesheet" href="assets/vendor/overlay-scroll/OverlayScrollbars.min.css" />
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/css/selectize.bootstrap3.min.css" integrity="sha256-ze/OEYGcFbPRmvCnrSeKbRTtjG4vGLHXgOqsyLFTRjg=" crossorigin="anonymous" />
		<link rel="stylesheet" href="assets/css/admin.css" />
	</head>

	<body class="backgroundColorChange" onload="">

		<!-- Page wrapper start -->
		<div class="page-wrapper">

			<!-- Main container start -->
			<div class="main-container">
				<?php
				require "adminSideBar.php";
				?>

				<!-- App container starts -->
				<div class="app-container">
					<!-- App header starts -->
					<?php

					require "adminAppHeader.php";
					?>
					<!-- App header ends -->

					<!-- App hero header starts -->
					<div class="app-hero-header d-flex align-items-start">

						<!-- Breadcrumb start -->
						<ol class="breadcrumb d-none d-lg-flex align-items-center">
							<li class="breadcrumb-item">
								<i class="bi bi-house text-dark"></i>
								<a href="adminPanel.php">Home</a>
							</li>
							<li class="breadcrumb-item" aria-current="page">Profile Status</li>
						</ol>
						<!-- Breadcrumb end -->

					</div>
					<!-- App Hero header ends -->

					<!-- App body starts -->
					<div class="app-body" id="cbody">
						<?php

						$userResultAttendance = Database::operation("SELECT * FROM `user`  WHERE  `user_status_id`='1'", "s");

						?>

						<div class="row">
							<div class="col-12 col-lg-4">

								<div class="card shadow mb-4">
									<div class="card-header">
										<h5 class="card-title">Overall Profile Status</h5>
									</div>
									<div class="card-body">
										<div id="device"></div>
										<div class="text-center my-4">
											<h2 class="text-success" id="successPresentage">


											</h2>

										</div>
									</div>
								</div>

							</div>

							<div class="col-12 col-lg-8">
								<div class="card mb-4">
									<div class="card-body">
										<div class="row">

											<div class="table-responsive">
												<table class="table align-middle table-hover m-0">
													<thead>
														<tr>
															<th scope="col">No</th>
															<th scope="col">Id</th>
															<th scope="col">Name</th>

															<th scope="col">Email</th>
															<th scope="col"></th>

														</tr>
													</thead>
													<tbody>

														<?php
														if ($userResultAttendance->num_rows != 0) {


															$count = 0;

															$allCompletedCount = 0;
															while ($userRow = $userResultAttendance->fetch_assoc()) {

																$count++;
																$profileStatusCount = 0;
																if ($userRow["fname"] != null && !empty($userRow["fname"])) {
																	$profileStatusCount++;
																}


																if ($userRow["lname"] != null && !empty($userRow["lname"])) {
																	$profileStatusCount++;
																}

																if ($userRow["email"] != null && !empty($userRow["email"])) {
																	$profileStatusCount++;
																}


																if ($userRow["mobile"] != null && !empty($userRow["mobile"])) {
																	$profileStatusCount++;
																}


																if ($userRow["jid"] != null && !empty($userRow["jid"])) {
																	$profileStatusCount++;
																}

																if ($userRow["dob"] != null && !empty($userRow["dob"])) {
																	$profileStatusCount++;
																}


																if ($userRow["nic"] != null && !empty($userRow["nic"])) {
																	$profileStatusCount++;
																}


																if ($userRow["duration"] != null && !empty($userRow["duration"])) {
																	$profileStatusCount++;
																}


																if ($userRow["linkdin"] != null && !empty($userRow["linkdin"])) {
																	$profileStatusCount++;
																}

																
																if ($userRow["type_id"] == "1" || $userRow["type_id"] == "2" || $userRow["type_id"] == "4") {
																	if ($userRow["months"] != null && $userRow["months"]>0) {
																		$profileStatusCount++;
																		
																	}
																} else {
																	$profileStatusCount++;
																}



																$addressResult = Database::operation("SELECT * FROM `address`  WHERE `user_id`='" . $userRow["id"] . "'", "s");


																if ($addressResult->num_rows != 0) {
																	$profileStatusCount++;
																}


																$id_image = Database::operation("SELECT * FROM `id_image` WHERE `user_id`='" . $userRow["id"] . "'", "s");


																if ($id_image->num_rows != 0) {
																	$profileStatusCount++;
																}



																$profile_image = Database::operation("SELECT * FROM `profile_image` WHERE `user_id`='" . $userRow["id"] . "'", "s");


																if ($profile_image->num_rows != 0) {
																	$profileStatusCount++;
																}

																$presentage = 0;
																if ($profileStatusCount == 13) {
																	$presentage = 100;
																} else {

																	$presentage = ($profileStatusCount / 13) * 100;
																	$presentage = number_format((float)$presentage, 2, '.', '');
																}


																$allCompletedCount += $profileStatusCount;




														?>
																<tr onclick="window.location='adminUserDetails.php?userEmail=<?php echo $userRow['email'] ?>'" style="cursor: pointer;">
																	<td><?php echo $count ?></td>
																	<td><?php echo $userRow["jid"] ?></td>
																	<td><?php echo $userRow["fname"] . " " . $userRow["lname"] ?></td>
																	<td><?php echo $userRow["email"] ?></td>
																	<td>
																		<div class="card shadow mb-4 ">
																			<div class="card-body">
																				<div class="d-flex justify-content-between mb-2">
																					<span class="d-none d-lg-block">Profile Status</span>
																					<span class="text-primary fw-bold"><?php echo $presentage ?> %</span>
																				</div>
																				<div class="progress small ">
																					<div class="progress-bar bg-primary" role="progressbar" style="width:<?php echo $presentage ?>%"
																						aria-valuenow="<?php echo $presentage ?>" aria-valuemin="0" aria-valuemax="100"></div>
																				</div>
																			</div>
																		</div>
																	</td>
																</tr>

															<?php




															}

															$allFieldCount = 13 * $count;
															$Allpresentage = ($allCompletedCount / $allFieldCount) * 100;
															$allvalue = 0;
															if ($Allpresentage == 100) {
																$allvalue = 100;
															} else {
																$allvalue = number_format((float)$Allpresentage, 2, '.', '');
															}



															$notAllCompleted = 100 - $allvalue;
															?>
															<script src="assets/vendor/apex/apexcharts.min.js"></script>
															<script>
																var complete = <?php echo $allvalue ?>;
																var incomplete = <?php echo $notAllCompleted ?>;

																var options = {
																	chart: {
																		height: 300,
																		type: "donut",
																	},
																	labels: ["Complete", "InComplete"],
																	series: [complete, incomplete],
																	legend: {
																		position: "bottom",
																	},
																	dataLabels: {
																		enabled: false,
																	},
																	stroke: {
																		width: 8,
																		colors: ["#ffffff"],
																	},
																	colors: ["#008000", "#FF0000"],
																	tooltip: {
																		y: {
																			formatter: function(val) {
																				return val + " %";
																			},
																		},
																	},
																};
																var chart = new ApexCharts(document.querySelector("#device"), options);
																chart.render();
																document.getElementById("successPresentage").innerHTML = complete + " %";
															</script>
														<?php

														}

														?>

													</tbody>
												</table>
											</div>
										</div>
										<div class="row mt-3">
											<div class="col-12 text-center">
												<!-- Card start -->
												<div class="card mb-4">
													<div class="card-body">
														<div class="btn-group" role="group" aria-label="Basic checkbox toggle button group" id="pagicontainer">

														</div>
													</div>
												</div>
												<!-- Card end -->
											</div>
										</div>
									</div>
								</div>

							</div>
						</div>


						<!-- Row end -->

					</div>
					<!-- App body ends -->

					<!-- App footer start -->
					<div class="app-footer">
						<span>© 2024 Jadetimes Media LLC. All rights reserved.</span>
					</div>
					<!-- App footer end -->

				</div>
				<!-- App container ends -->

			</div>
			<!-- Main container end -->

		</div>
		<!-- Page wrapper end -->

		<!-- *************
			************ JavaScript Files *************
		************* -->
		<!-- Required jQuery first, then Bootstrap Bundle JS -->
		<script src="assets/js/jquery.min.js"></script>
		<script src="assets/js/bootstrap.bundle.min.js"></script>

		<!-- *************
			************ Vendor Js Files *************
		************* -->

		<!-- Overlay Scroll JS -->
		<script src="assets/vendor/overlay-scroll/jquery.overlayScrollbars.min.js"></script>
		<script src="assets/vendor/overlay-scroll/custom-scrollbar.js"></script>

		<!-- Custom JS files -->
		<script src="assets/js/custom.js"></script>

		<script src="assets/js/admin.js"></script>
		<!-- Bootstrap JS and dependencies -->
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


		<script src="assets/vendor/overlay-scroll/jquery.overlayScrollbars.min.js"></script>
		<script src="assets/vendor/overlay-scroll/custom-scrollbar.js"></script>

		<!-- Custom JS -->
		<script>
			function addNewArticleAdmin() {
				var msg = document.getElementById("infoMessage");
				var title = document.getElementById("title");
				var writerId = document.getElementById("writerId");
				var date = document.getElementById("date");
				var articleType = document.getElementById("articleType");


				if (writerId.value == 0) {
					msg.innerHTML = "Please Select A Writer";
					msg.classList = "alert alert-danger";
				} else if (!date.value) {

					msg.innerHTML = "Please Select A Date";
					msg.classList = "alert alert-danger";

				} else if (articleType.value == 0) {

					msg.innerHTML = "Please select an Article Type";
					msg.classList = "alert alert-danger";

				} else if (!title.value) {

					msg.innerHTML = "Title  is Empty";
					msg.classList = "alert alert-danger";

				} else {

					var formData = new FormData();
					formData.append("title", title.value);
					formData.append("writer", writerId.value);
					formData.append("date", date.value);
					formData.append("articleType", articleType.value);

					fetch(baseUrl + "adminArticleSubmittProcess.php", {
							method: "POST",
							body: formData,

						})
						.then(function(resp) {

							try {
								let response = resp.json();
								return response;
							} catch (error) {
								msg.classList = "alert alert-danger";
								msg.innerHTML = "Something wrong please try again";
								emailField.classList = "form-control";
								passwordField.classList = "form-control";
							}

						})
						.then(function(value) {

							if (value.type == "error") {
								msg.classList = "alert alert-danger";
								msg.innerHTML = value.message;

							} else if (value.type == "success") {
								msg.classList = "alert alert-success";
								msg.innerHTML = value.message;

								setTimeout(() => {
									window.location = "manageArticles.php";
								}, 1000);
							} else {
								msg.classList = "alert alert-danger";
								msg.innerHTML = "Something wrong please try again";
								emailField.classList = "form-control";
								passwordField.classList = "form-control";
							}

						})
						.catch(function(error) {
							console.log(error);
						});


				}
			}
		</script>

	</body>

	</html>
<?php

} else {
?>
	<script>
		window.location = "adminLogin.php"
	</script>
<?php
}
?>