<?php
session_start();
require "connection.php";
if (isset($_SESSION["jd_admin"])) {



	$admin = $_SESSION["jd_admin"];
	if (isset($_GET["userEmail"]) == null) {
?>
		<script>
			window.location = "manageStaff.php"
		</script>
	<?php

	}

	$userEmail = $_GET["userEmail"];



	$autoGeneratedPassword = uniqid() . $admin["id"];

	$d = new DateTime();
	$tz = new DateTimeZone("Asia/Colombo");
	$d->setTimezone($tz);
	$today = $d->format("Y-m-d");


	$userProfile = "";
	$paypentProfileResult = Database::operation("SELECT `user`.`id`,`user`.`fname`,`user`.`lname`,`staff`.`reg_date`,`user`.`email`,`staff`.`type`,`staff`.`earning`,`staff`.`month_start`,`staff`.`salary` FROM `staff` INNER JOIN `user` ON `user`.`id`=`staff`.`user_id` WHERE `user`.`email`='" . $userEmail . "'", "s");
	if ($paypentProfileResult->num_rows != 0) {
		$userProfile = $paypentProfileResult->fetch_assoc();
	} else {

	?>
		<script>
			window.location = "manageStaff.php"
		</script>
	<?php

	}

	?>

	<!DOCTYPE html>
	<html lang="en">

	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<title>Jade Times - Manage Staff Profile / admin</title>

		<!-- Meta -->
		<meta name="description" content="Marketplace for Bootstrap Admin Dashboards" />
		<meta name="author" content="Bootstrap Gallery" />
		<link rel="canonical" href="https://www.bootstrap.gallery/">
		<meta property="og:url" content="https://www.bootstrap.gallery">
		<meta property="og:title" content="Admin Templates - Dashboard Templates | Bootstrap Gallery">
		<meta property="og:description" content="Marketplace for Bootstrap Admin Dashboards">
		<meta property="og:type" content="Website">
		<meta property="og:site_name" content="Bootstrap Gallery">
		<link rel="icon" href="assets/img/iconImg.jpg" />

		<!-- *************
			************ CSS Files *************
		************* -->
		<link rel="stylesheet" href="assets/fonts/bootstrap/bootstrap-icons.css" />
		<link rel="stylesheet" href="assets/css/main.css" />

		<!-- *************
			************ Vendor Css Files *************
		************ -->

		<!-- Scrollbar CSS -->
		<link rel="stylesheet" href="assets/vendor/overlay-scroll/OverlayScrollbars.min.css" />
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/css/selectize.bootstrap3.min.css" integrity="sha256-ze/OEYGcFbPRmvCnrSeKbRTtjG4vGLHXgOqsyLFTRjg=" crossorigin="anonymous" />
		<link rel="stylesheet" href="assets/css/admin.css" />
	</head>

	<body class="backgroundColorChange">

		<!-- Page wrapper start -->
		<div class="page-wrapper">

			<!-- Main container start -->
			<div class="main-container">
				<?php
				require "adminSideBar.php";
				?>

				<!-- App container starts -->
				<div class="app-container">
					<!-- App header starts -->
					<?php

					require "adminAppHeader.php";
					?>
					<!-- App header ends -->

					<!-- App hero header starts -->
					<div class="app-hero-header d-flex align-items-start">

						<!-- Breadcrumb start -->
						<ol class="breadcrumb d-none d-lg-flex align-items-center">
							<li class="breadcrumb-item">
								<i class="bi bi-house text-dark"></i>
								<a href="adminPanel.php">Home</a>
							</li>
							<li class="breadcrumb-item">
								<i class="bi bi-currency-dollar text-dark"></i>
								<a href="manageStaff.php">Payments</a>
							</li>
							<li class="breadcrumb-item" aria-current="page">Manage Payment Profile</li>

						</ol>
						<!-- Breadcrumb end -->

					</div>
					<!-- App Hero header ends -->

					<!-- App body starts -->
					<div class="app-body" id="cbody">



						<div class="row">
							<div class="col-md-3 col-sm-6 col-12">
								<div class="card shadow mb-4">
									<div class="card-body text-center">

										<?php

										$imgResult = Database::operation("SELECT * FROM `profile_image` WHERE `user_id`='" . $userProfile["id"] . "'", "s");
										if ($imgResult->num_rows != 0) {
											$image = $imgResult->fetch_assoc();
										?>
											<img src="resources/profileImg/<?php echo $image["name"] ?>" class="img-6x rounded-circle mb-4" alt="Admin Dashboard" />
										<?php
										} else {
										?>
											<img src="assets/img/defaultProfileImage.png" class="img-6x rounded-circle mb-4" alt="Admin Dashboard" />
										<?php
										}
										?>

										<h5 class="mb-3"><?php echo $userProfile["fname"] . " " . $userProfile["lname"] ?></h5>

									</div>
									<div class="card-footer text-center">
										<a href="#" class="text-red"><?php
																		if ($userProfile["type"] == null || $userProfile["type"] == 0) {
																			echo "Contributor";
																		} else {
																			echo "Staff Member";
																		}
																		?></a>
									</div>
								</div>
							</div>
							<div class="col-md-5 col-sm-6 col-12">
								<div class="card shadow ">
									<div class="card-header">
										<h5 class="card-title">Earnings</h5>
									</div>
									<div class="card-body">
										<div id="weekly-sales"></div>
										<div class="text-center my-4">
											<h1 class="fw-bold">
												<?php if ($userProfile["earning"] == null) {
													echo 0;
												} else {
													echo "$ " . $userProfile["earning"];
												} ?>
												<i class="bi bi-arrow-up-right-circle-fill text-success"></i>
											</h1>
											<!-- <p class="fw-light m-0">21% higher than last month</p> -->
										</div>
									</div>
								</div>
							</div>
							<?php
							if ($userProfile["type"] == null || $userProfile["type"] == 0) {
							?>
								<div class="col-md-4 col-sm-12 col-12">
									<!-- Card start -->

									<div class="card shadow mb-4">

										<div class="card-body">
											<h5 class="card-title">Make a Payment </h5>
											<div class="col-12 alert alert-danger d-none" id="infoMessagePaymentUpdate" role="alert">
											</div>
											<div class="mb-3 mt-3">
												<label for="contactNumber" class="form-label">Payment(USD)</label>
												<input type="number" class="form-control" id="customPrice"
													placeholder="payment in USD" />
											</div>
											<div class="mb-3 mt-3">
												<label for="contactNumber" class="form-label">Description</label>

												<textarea name="" id="customDesc" class="form-control" placeholder="Describe the Payment"></textarea>
											</div>

											<button class="btn btn-primary backgroundColorChange rounded-0" onclick="addAPayment()">Submit</button>

										</div>
									</div>

									<!-- Card end -->
								</div>
							<?php
							}
							?>


						</div>


						<div class="row">
							<div class="col-xxl-12">
								<div class="card shadow mb-4">
									<div class="card-body">
										<div class="custom-tabs-container">
											<ul class="nav nav-tabs" id="customTab2" role="tablist">
												<li class="nav-item" role="presentation">
													<a class="nav-link active" id="tab-oneA" data-bs-toggle="tab" href="#oneA" role="tab"
														aria-controls="oneA" aria-selected="true">Payment History</a>
												</li>
												<li class="nav-item" role="presentation">
													<a class="nav-link" id="tab-twoA" data-bs-toggle="tab" href="#twoA" role="tab"
														aria-controls="twoA" aria-selected="false">Settings</a>
												</li>

											</ul>
											<div class="tab-content">
												<div class="tab-pane fade show active" id="oneA" role="tabpanel">
													<!-- Row start -->
													<div class="row">
														<div class="col-12">
															<div class="table-responsive">
																<table class="table align-middle table-bordered m-0">
																	<thead>
																		<tr>
																			<th>id</th>
																			<th>Type</th>
																			<th>Description</th>
																			<th>Payment</th>
																			<th>Date</th>

																		</tr>
																	</thead>
																	<tbody>
																		<?php
																		$userResult = Database::operation("SELECT `payment`.`type`,`payment`.`description`,`payment`.`price`,`payment`.`date`  FROM `staff` INNER JOIN `payment` ON `payment`.`staff_id`=`staff`.`id` WHERE `staff`.`user_id`='" . $userProfile["id"] . "'", "s");


																		if ($userResult->num_rows != 0) {

																			$num = 1;
																			while ($row = $userResult->fetch_assoc()) {
																		?>
																				<tr>
																					<td><?php echo $num ?></td>
																					<td><?php
																						if ($row["type"] == 1) {
																							echo "salary";
																						} else {
																							echo "Project Base Payment";
																						}
																						?></td>
																					<td><?php echo $row["description"] ?></td>
																					<td><?php echo "$ " . $row["price"] ?></td>
																					<td><?php echo $row["date"] ?></td>
																				</tr>
																			<?php
																				$num++;
																			}
																		} else {
																			?>
																			<tr>
																				<td colspan="5">"oops !! you got nothing"</td>

																			</tr>
																		<?php

																		}
																		?>

																	</tbody>
																</table>
															</div>
														</div>
													</div>
												</div>
												<div class="tab-pane fade" id="twoA" role="tabpanel">
													<!-- Row start -->
													<div class="row">
														<div class="col-sm-12 col-12">
															<!-- Card start -->
															<div class="card">
																<div class="card-body">
																	<div class="col-12 alert alert-danger d-none" id="infoMessage" role="alert">
																	</div>
																	<div class="row">

																		<div class="col-12 col-md-6 m-auto">
																			<div class="row">
																				<div class="col-12">
																					<div class="card shadow mb-4">

																						<div class="card-body">
																							<h5 class="card-title colorRed">ONLY APPLICABLE FOR PERMENET STAFF</h5>


																							<div class="form-check form-switch m-0 mt-3 d-none">
																								STAFF MAMBER
																								<input class="form-check-input" type="checkbox" role="switch" id="switchFour" />
																							</div>
																							<div class="mb-3 mt-3">
																								<label for="contactNumber" class="form-label">Payment Calculation Start Date <br>(Current Month)</label>
																								<input type="date" class="form-control" id="payStartMonth"
																									placeholder="Contact" <?php
																															if ($userProfile["type"] == null || $userProfile["type"] == 0) {
																																echo "disabled";
																															} else {
																																echo 'value=' . $userProfile["month_start"];
																															}
																															?> />
																							</div>
																							<div class="mb-3">
																								<label for="contactNumber" class="form-label">Salary In USD</label>
																								<input type="number" class="form-control" id="salary"
																									placeholder="Salary" <?php
																															if ($userProfile["type"] == null || $userProfile["type"] == 0) {
																																echo "disabled";
																															} else {
																																echo "value=" . $userProfile["salary"];
																															}
																															?> />
																							</div>

																						</div>
																					</div>
																				</div>
																			</div>





																		</div>
																		<div class="col-12 col-md-6 ">
																			<div class="row">
																				<div class="col-12">
																					<div class="mb-3">
																						<label for="fullName" class="form-label">Payment Profile Create Date</label>
																						<input type="date" class="form-control" id="regDate" placeholder="" value="<?php echo $userProfile["reg_date"] ?>" />
																					</div>
																				</div>
																			</div>
																			<!-- Form Field Start -->


																			<!-- Form Field Start -->

																		</div>


																	</div>
																</div>
															</div>
															<!-- Card end -->
														</div>

													</div>
													<!-- Row end -->
													<div class="d-flex gap-2 mt-4 justify-content-center">

														<button type="button" class="btn btn-primary backgroundColorChange rounded-0 ms-5" onclick="updateThePaymentProfile()">
															Update The Payment Profile
														</button>
													</div>
												</div>

											</div>
										</div>
									</div>
								</div>
							</div>
						</div>

						<!-- Row end -->




					</div>
					<!-- App body ends -->

					<!-- App footer start -->
					<div class="app-footer">
						<span>© 2024 Jadetimes Media LLC. All rights reserved.</span>
					</div>
					<!-- App footer end -->

				</div>
				<!-- App container ends -->

			</div>
			<!-- Main container end -->

		</div>
		<!-- Page wrapper end -->

		<!-- *************
			************ JavaScript Files *************
		************* -->
		<!-- Required jQuery first, then Bootstrap Bundle JS -->
		<script src="assets/js/jquery.min.js"></script>
		<script src="assets/js/bootstrap.bundle.min.js"></script>

		<!-- *************
			************ Vendor Js Files *************
		************* -->

		<!-- Overlay Scroll JS -->
		<script src="assets/vendor/overlay-scroll/jquery.overlayScrollbars.min.js"></script>
		<script src="assets/vendor/overlay-scroll/custom-scrollbar.js"></script>

		<!-- Custom JS files -->
		<script src="assets/js/custom.js"></script>

		<script src="assets/js/admin.js"></script>
		<!-- Bootstrap JS and dependencies -->
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


		<!-- Custom JS -->
		<script>
			function addAPayment() {

				var price = document.getElementById("customPrice");
				var customDesc = document.getElementById("customDesc");

				let msg = document.getElementById("infoMessagePaymentUpdate");


				var url = new URL(window.location.href);
				var userEmail = url.searchParams.get("userEmail");

				if (userEmail == null) {
					window.location = "manageStaff.php";
				}

				if (!price.value || price.value <= 0) {

					msg.innerHTML = "Please Add A Valid Payment";
					msg.classList = "alert alert-danger";

				} else if (!customDesc.value) {
					msg.innerHTML = "Please Describe The Payment";
					msg.classList = "alert alert-danger";

				} else {
					var formData = new FormData();
					formData.append("userEmail", userEmail);
					formData.append("customDesc", customDesc.value);
					formData.append("price", price.value);

					fetch(baseUrl + "customPaymentUpdate.php", {
							method: "POST",
							body: formData,


						}).then(function(resp) {
							return resp.json();

						})
						.then(function(value) {

							if (value.type == "success") {

								msg.innerHTML = value.message;
								msg.classList = "alert alert-success";

								setTimeout(function() {
									window.location = "staffProfile.php?userEmail=" + userEmail;
								}, 2000);



							} else if (value.type = "error") {

								msg.innerHTML = value.message;
								msg.classList = "alert alert-danger";
								backToTop(msg);

							}
						})
						.catch(function(error) {
							console.log(error);
						});
				}



			}

			function updateThePaymentProfile(type) {

				var url = new URL(window.location.href);
				var userEmail = url.searchParams.get("userEmail");
				var msg = document.getElementById("infoMessage");
				if (userEmail == null) {
					window.location = "manageStaff.php";
				}
				var payStartMonth = document.getElementById("payStartMonth");
				var salary = document.getElementById("salary");
				var regDate = document.getElementById("regDate");



				if (type == 1 && !payStartMonth.value) {

					msg.innerHTML = "Please Select A Date";
					msg.classList = "alert alert-danger";

				} else if (type == 1 && !salary.value == 0) {

					msg.innerHTML = "Update The Salary";
					msg.classList = "alert alert-danger";

				} else if (!regDate.value) {

					msg.innerHTML = "Payment Profile Create Date Is Empty";
					msg.classList = "alert alert-danger";

				} else {

					var formData = new FormData();
					formData.append("payStartMonth", payStartMonth.value);
					formData.append("salary", salary.value);
					formData.append("regDate", regDate.value);
					formData.append("userEmail", userEmail);

					fetch(baseUrl + "adminupdatePaymentProcess.php", {
							method: "POST",
							body: formData,

						})
						.then(function(resp) {

							try {
								let response = resp.json();
								return response;
							} catch (error) {
								msg.classList = "alert alert-danger";
								msg.innerHTML = "Something wrong please try again";
								emailField.classList = "form-control";
								passwordField.classList = "form-control";
							}

						})
						.then(function(value) {

							if (value.type == "error") {
								msg.classList = "alert alert-danger";
								msg.innerHTML = value.message;

							} else if (value.type == "success") {
								msg.classList = "alert alert-success";
								msg.innerHTML = value.message;

								setTimeout(() => {
									window.location = "staffProfile.php?userEmail=" + userEmail;
								}, 1000);
							} else {
								msg.classList = "alert alert-danger";
								msg.innerHTML = "Something wrong please try again";
								emailField.classList = "form-control";
								passwordField.classList = "form-control";
							}

						})
						.catch(function(error) {
							console.log(error);
						});


				}
			}


			function loadStaffProfile(stat) {


				var selectUser = document.getElementById("select-state");

				var from = document.getElementById("from");
				var to = document.getElementById("to");
				var status = document.getElementById("status");




				var ele = document.getElementsByName('btnradio');
				var dip = ""
				for (i = 0; i < ele.length; i++) {
					if (ele[i].checked) {
						dip = ele[i].value;
					}

				}
				var page = 1;

				if (stat == 2) {
					var pagi = document.getElementsByName('pagi');

					for (j = 0; j < pagi.length; j++) {
						if (pagi[j].checked) {
							page = Number(pagi[j].value);
						}

					}
				}


				var formData = new FormData();
				formData.append("selectUser", selectUser.value);
				formData.append("from", from.value);
				formData.append("to", to.value);

				formData.append("order", dip);
				formData.append("status", status.value);
				formData.append("page", page);






				var tablebody = document.getElementById("tableBodyUser");
				tablebody.innerHTML = "";
				fetch(baseUrl + "staffDetailsLoadProcess.php", {
						method: "POST",
						body: formData,


					}).then(function(resp) {
						return resp.json();

					})
					.then(function(value) {

						var pagicontainer = document.getElementById('pagicontainer');
						pagicontainer.innerHTML = "";

						if (value.type == "success") {
							var userSearchData = value.message;

							for (let index = 0; index < userSearchData.length; index++) {
								const user = userSearchData[index];

								const newRow = document.createElement('tr');
								const nocell = document.createElement('td');
								nocell.textContent = index + 1;
								const idCell = document.createElement('td');
								idCell.textContent = user[3];

								const roleCell = document.createElement('td');
								roleCell.textContent = user[0] + " " + user[1] + " " + user[2];

								const addressCell = document.createElement('td');
								addressCell.textContent = user[5];

								const endDateCell = document.createElement('td');
								endDateCell.textContent = user[4];

								const date = document.createElement('td');
								date.textContent = user[6];

								const salaryCell = document.createElement('td');

								if (user[7] == 1) {
									salaryCell.innerText = "Commercial";
									salaryCell.classList = "bg-danger-subtle text-black text-center";
								} else if (user[7] == 2) {
									salaryCell.innerText = "non Commercial";
									salaryCell.classList = "text-black text-center";
								}



								newRow.appendChild(nocell);
								newRow.appendChild(idCell);
								newRow.appendChild(roleCell);
								newRow.appendChild(addressCell);


								newRow.appendChild(endDateCell);
								newRow.appendChild(date);
								newRow.appendChild(salaryCell);

								tablebody.appendChild(newRow);
							}


							var btnCount = value.buttoncount;


							var firstpagi = document.createElement('input');
							firstpagi.type = 'radio';
							firstpagi.className = 'btn-check';
							firstpagi.name = 'pagi';
							firstpagi.id = 'firstpagi';

							firstpagi.value = 1;
							firstpagi.onchange = function() {
								loadUserArticles(2);
							}



							var firstlabel = document.createElement('label');
							firstlabel.className = 'btn btn-outline-info removeCorner';
							firstlabel.htmlFor = 'firstpagi';
							firstlabel.innerText = "First";



							pagicontainer.appendChild(firstpagi);
							pagicontainer.appendChild(firstlabel);



							var startPage = 1;

							var endpage = 5;



							var val = page + 4;





							if ((page + 4) < btnCount) {
								endpage = page + 4;
								startPage = page;

							} else {

								if (btnCount >= 5) {
									startPage = btnCount - 4;

								} else {

									startPage = 1;

								}
								endpage = btnCount;
							}



							if (page != 1 && btnCount > 5) {
								var frontPagi = document.createElement('input');
								frontPagi.type = 'radio';
								frontPagi.className = 'btn-check';
								frontPagi.name = 'pagi';
								frontPagi.id = 'btnpagifront';

								frontPagi.value = Number(startPage) - 1;
								frontPagi.onchange = function() {
									loadUserArticles(2);
								}

								var labelfrontpagi = document.createElement('label');
								labelfrontpagi.className = 'btn btn-outline-info removeCorner';
								labelfrontpagi.htmlFor = 'btnpagifront';
								labelfrontpagi.innerText = Number(startPage) - 1;



								pagicontainer.appendChild(frontPagi);
								pagicontainer.appendChild(labelfrontpagi);

							}

							for (let i = startPage - 1; i < endpage; i++) {



								var radioButton = document.createElement('input');
								radioButton.type = 'radio';
								radioButton.className = 'btn-check';
								radioButton.name = 'pagi';
								radioButton.id = 'btnpagi' + i;
								var pageVal = i + 1;
								radioButton.value = pageVal;
								radioButton.onchange = function() {
									loadUserArticles(2);
								}
								if (page == pageVal) {
									radioButton.checked = true;
								}


								var label = document.createElement('label');
								label.className = 'btn btn-outline-info removeCorner';
								label.htmlFor = 'btnpagi' + i;
								label.innerText = pageVal;



								pagicontainer.appendChild(radioButton);
								pagicontainer.appendChild(label);

							}


							var lastpagi = document.createElement('input');
							lastpagi.type = 'radio';
							lastpagi.className = 'btn-check';
							lastpagi.name = 'pagi';
							lastpagi.id = 'lastpagi';

							lastpagi.value = btnCount;
							lastpagi.onchange = function() {
								loadUserArticles(2);
							}



							var lastlabel = document.createElement('label');
							lastlabel.className = 'btn btn-outline-info removeCorner';
							lastlabel.htmlFor = 'lastpagi';
							lastlabel.innerText = "Last (" + btnCount + ")";



							pagicontainer.appendChild(lastpagi);
							pagicontainer.appendChild(lastlabel);




						} else if (value.type = "error") {

							tablebody.innerHTML = value.message;

						}
					})
					.catch(function(error) {
						console.log(error);
					});



			}
		</script>

	</body>

	</html>
<?php

} else {
?>
	<script>
		window.location = "adminLogin.php"
	</script>
<?php
}
?>